# Generated by Django 6.0 on 2026-01-16 13:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=accounts.models.generate_user_id, editable=False, max_length=100, unique=True),
        ),
    ]
