# Generated by Django 6.0 on 2026-01-11 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_author_blog_created_at_blog_parent_blog_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blogs.comment'),
        ),
    ]
