# Generated by Django 6.0 on 2026-01-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('owner', models.CharField(blank=True, default='Avihs Builders', max_length=255, null=True)),
                ('booked_for', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
