# Generated by Django 6.0 on 2026-01-15 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_plots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plot',
            name='booked_for',
            field=models.CharField(default='Not Booked', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='owner',
            field=models.CharField(default='Avihs Builders', max_length=255, null=True),
        ),
    ]
